### ISSUE TITLE
Remote loading of Table data

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/tableschema-jl#18]
As an extension of #11, ensure that Tables can be loaded from a remote location by HTTP URL.

**Comment by loleg** [comment]
@roll currently the library has no external dependencies, however the most reasonable way to implement this is using [HTTP for Julia](https://github.com/JuliaWeb/HTTP.jl). I've added example code, which looks like this:

```
mytable = Table()
req = request("GET", "https://...")
read(mytable, readcsv(req.body))
```

Is it really a requirement to bake this into our lib?

**Comment by roll** [comment]
@loleg 
The general approach of the libs is to simplify user experience e.g.:
```python
table = Table(path.csv/path.xls/url/dict/etc)
```
but if it's a common practice to use `req.body` in Julia it should be OK while the functionality is here (an ability to open a remote table).

I don't how dependencies are handled in Julia (maybe some gotchas for clients) but in general to do not have dependencies (esp. such vital as HTTP requests) is not really a goal for other libs. For example, the Python one has a lot of dependencies.

**Comment by loleg** [comment]
Working and tested.
