### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by scls19fr** [frictionlessdata/tableschema-jl#23]
Hello,

It will be nice to enable CI for this repository.

Kind regards

PS : you will probably have to first tackle https://github.com/frictionlessdata/datapackage-jl/issues/12

**Comment by loleg** [comment]
@roll I don't have sufficient rights to enable Travis-CI, but the project is set up for builds and tested on my [own repository](https://travis-ci.org/loleg/TableSchema.jl/). Therefore assigning to you.

**Comment by roll** [comment]
@scls19fr @loleg 
I've just enabled it.

**Comment by roll** [comment]
Maybe we have to tweak it slightly because it fails for now - https://travis-ci.org/frictionlessdata/tableschema-jl/jobs/435473309

**Comment by roll** [comment]
Also, enabled it on coveralls.io

**Comment by scls19fr** [comment]
https://travis-ci.org/frictionlessdata/tableschema-jl/jobs/435473309#L452

is broken because of

https://github.com/frictionlessdata/datapackage-jl/issues/12

**Comment by roll** [comment]
@scls19fr 
Ok, thanks. I guess @serahrono will update it soon.
