### ISSUE TITLE
Read and validate a table schema descriptor

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/tableschema-jl#6]
A Table Schema is represented by a **descriptor**, which can be read from a dictionary or JSON object (e.g. file). See [full specs](http://frictionlessdata.io/specs/table-schema/#descriptor) for details and [table-schema.json](https://frictionlessdata.io/schemas/table-schema.json) for validation schema.

- [x] Standard parts of the descriptor are validated on loading.
- [x] Errors from validation are handled in a standard way. 
- [x] *Field Descriptors* are loaded (type validation will be done later).
- [x] Tests cover the basic descriptor design and reading scenarios.

**Comment by loleg** [comment]
@roll by "standard validation", would it be sufficient to test in native code, or do you expect to validate each time against [JSON schema](https://frictionlessdata.io/schemas/table-schema.json)?

**Comment by roll** [comment]
@loleg 
Python/JavaScript/etc validate against JSON Schema - https://frictionlessdata.io/schemas/table-schema.json

**Comment by loleg** [comment]
Yes, but Julia's JSON libraries currently lack a validator, so we would need to address https://github.com/JuliaIO/JSON.jl/issues/238 first.

**Comment by roll** [comment]
@loleg 
If it's not available for the platform (Julia) at the moment any other options should work. E.g. testing in code.

**Comment by loleg** [comment]
Validation was added in https://github.com/frictionlessdata/tableschema-jl/pull/14 and completed in https://github.com/frictionlessdata/tableschema-jl/pull/16
